### ISSUE TITLE
Add  auto-incremental fields

### ISSUE THREAD

**Issue by taromero** [percolatestudio/meteor-factory#2]
Helpful for generating sequence of e.g. ids or names.

For example:

``` javascript
Factory.define('place', Places, {
  name: Factory.autoIncrement('Place')
})

Factory.build('place') // returns { name: 'Place 0' }
Factory.build('place') // returns { name: 'Place 1' }
Factory.build('place') // returns { name: 'Place 2' }
```

**Comment by user453584** [comment]
I have a similar use case. For tests, I'd like to [something like this](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#sequences), but in meteor.

Since one should use predictable/repeatable data in tests, the fake library is not an option here.

Where did this issue end up? What's the recommended way of doing this?

**Comment by dburles** [comment]
Hey guys, I've just added a sequence method to `0.3.8`, I'm yet to update the docs, but here's the basic usage:

```js
Factory.define('author', Authors, {
    name: 'John Smith',
    email: function(factory) {
      return factory.sequence(function(n) {
        return 'person' + n + '@example.com';
      });
    }
  });
```

**Comment by dburles** [comment]
@user453584 let me know how it goes
